name: Run reproducer on each commit
on: push
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: 11
    - uses: gradle/gradle-build-action@v2
      name: Run without verifying metadata
      with:
        arguments: help --info
    - uses: gradle/gradle-build-action@v2
      name: Write verification metadata
      with:
        arguments: --write-verification-metadata sha256 help --info